mongodb/go-client-mongodb-ops-manager

Makefile, go.mod, go.sum, opsmngr/automation_config.go, opsmngr/automation_status.go, opsmngr/opsmngr.go, opsmngr/opsmngr_test.go, opsmngr/organizations.go, opsmngr/projects.go, opsmngr/unauth_users.go
_Jira ticket:_ [CLOUDP-58630](https://jira.mongodb.org/browse/CLOUDP-58630)
=> CLOUDP-58630: Add alerts to the ops manager go client

opsmngr/opsmngr.go
_Jira ticket:_ [CLOUDP-58939](https://jira.mongodb.org/browse/CLOUDP-58939)
=> CLOUDP-58939: Add restore jobs to OM go client

opsmngr/automation_config.go
_Jira ticket:_ [CLOUDP-59299](https://jira.mongodb.org/browse/CLOUDP-59299)
=> CLOUDP-59299: Update the Auth config for the automation config to support users

opsmngr/all_clusters.go, opsmngr/opsmngr.go
_Jira ticket:_ [CLOUDP-59563](https://jira.mongodb.org/browse/CLOUDP-59563)
=> CLOUDP-59563: Adding atlas.Alerts to the ops manager client

search/example_search_test.go, search/search.go, search/search_test.go
_Jira ticket:_ [CLOUDP-60378](https://jira.mongodb.org/browse/CLOUDP-60378)
This is an initial work to start bringing the common automation config features to this lib
=> CLOUDP-60378: Move search pck to opsmngr client repo

opsmngr/host_databases.go, opsmngr/host_databases_test.go, opsmngr/opsmngr.go
_Jira ticket:_ [CLOUDP-60180](https://jira.mongodb.org/browse/CLOUDP-60180)
=> CLOUDP-60180: Implement the databases API OM

opsmngr/automation_config.go
_Jira ticket:_ [CLOUDP-61086](https://jira.mongodb.org/browse/CLOUDP-61086)
=> CLOUDP-61086: Typing the indexconfig in the OM go client

opsmngr/clusters_test.go, opsmngr/logs.go, opsmngr/logs_test.go, opsmngr/opsmngr.go
_Jira ticket:_ [CLOUDP-60952](https://jira.mongodb.org/browse/CLOUDP-60952)
**Create**:
```
{
"id": "5ea1637e388ab201fcf24236"
}
```
**List**: 
```
{
"links": [
{
"rel": "self",
"href": "http://localhost:8080/api/public/v1.0/groups/5ea060049ccffa4bcdb17883/logCollectionJobs?verbose=true\u0026pageNum=1\u0026itemsPerPage=100"
}
],
"results": [
{
"id": "5ea1637e388ab201fcf24236",
"groupId": "5ea060049ccffa4bcdb17883",
"userId": "5ea15f3d388ab201fcf2385e",
"creationDate": "2020-04-23T09:44:30Z",
"expirationDate": "2020-05-23T09:44:30Z",
"status": "SUCCESS",
"resourceType": "replicaset",
"resourceName": "myReplicaSet",
"rootResourceName": "myReplicaSet",
"rootResourceType": "replicaset",
"downloadUrl": "http://localhost:8080/api/public/v1.0/groups/5ea060049ccffa4bcdb17883/logCollectionJobs/5ea1 …
```
=> CLOUDP-60952: Implement the log collection API for the OM go client

opsmngr/automation_config.go, opsmngr/automation_config_test.go
_Jira ticket:_ [CLOUDP-61611](https://jira.mongodb.org/browse/CLOUDP-61611)
Response:
```
{
"automationAgentVersion": "10.14.0.6306-1",
"biConnectorVersion": "2.13.4"
}
```
=> CLOUDP-61611: Implement api to update agents in the om go client

opsmngr/diagnostics.go, opsmngr/diagnostics_test.go, opsmngr/logs_test.go, opsmngr/opsmngr.go
_Jira ticket:_ [CLOUDP-60953](https://jira.mongodb.org/browse/CLOUDP-60953)
=> CLOUDP-60953: Implement download diagnose archive API, OM client

opsmngr/agent_api_keys.go, opsmngr/agents.go, opsmngr/all_clusters.go, opsmngr/automation_config.go, opsmngr/automation_status.go, opsmngr/checkpoints.go, opsmngr/clusters.go, opsmngr/global_alerts.go, opsmngr/hosts.go, opsmngr/hosts_databases.go, opsmngr/hosts_databases_measurements.go, opsmngr/hosts_disks.go, opsmngr/hosts_disks_measurements.go, opsmngr/hosts_measurements.go, opsmngr/logs.go, opsmngr/opsmngr.go, opsmngr/organizations.go, opsmngr/projects.go, opsmngr/unauth_users.go
Use a common service type that can be reused for all our services
=> Create a service type that can reused for all services

opsmngr/organizations.go, opsmngr/organizations_test.go
_Jira ticket:_ [CLOUDP-62057](https://jira.mongodb.org/browse/CLOUDP-62057)
=> CLOUDP-62057: Add pagination to listing all projects in a orgs - om go client

opsmngr/automation.go, opsmngr/automation_config.go, opsmngr/automation_config_test.go, opsmngr/backup_agent_config.go, opsmngr/backup_agent_config_test.go, opsmngr/monitoring_agent_config.go, opsmngr/monitoring_agent_config_test.go
Add new methods for the endpoints related to agent config for backup and monitoring
=> Add agent config getters

opsmngr/automation_config.go, search/example_search_test.go, search/search.go, search/search_test.go
_Jira ticket:_ [CLOUDP-65729](https://jira.mongodb.org/browse/CLOUDP-65729)
=> CLOUDP-65729: Add sharded cluster support to Ops Manager

atmcfg/atmcfg.go, atmcfg/atmcfg_test.go
Add a generic function we can use to remove clusters from the automation config
=> feat: add a function to remove clusters from the automation config

README.md, opsmngr/doc.go, opsmngr/opsmngr.go
Updated doc. references to the library for Digest Auth.
=> Updated the references to the digest library

opsmngr/unauth_users.go
=> CLOUDP-65740: OM4.4 will return programmaticApiKey when creating an owner

opsmngr/automation_config.go, opsmngr/automation_config_test.go
_Jira ticket:_  CLOUDP-67986
Adding more optional fields
=> CLOUDP-67986: Improve automation config typing

.github/dependabot.yml, README.md, SECURITY.md, opsmngr/doc.go
_Jira ticket:_ CLOUDP-68051
- Add a dependabot
- Add how to get API keys
- Add a SECURITY.md file
=> CLOUDP-68051: Update ops manager client README

opsmngr/opsmngr.go
=> CLOUDP-67925: Implement programatic API key API in ops manager go client

opsmngr/projects.go
_Jira ticket:_ CLOUDP-68322
I was testing a new Ops Manager installation and saw we are missing a couple of things here
=> CLOUDP-68322: Add agent API key to project response

atmcfg/atmcfg.go, atmcfg/atmcfg_test.go, atmcfg/security.go, atmcfg/security_test.go, go.mod, go.sum
_Jira ticket:_ CLOUDP-59489
This was manually tested with ops manager and an evg run of the cli using this version of the lib
=> CLOUDP-59489: Generate scramsha credential using the same approach as ops manager

opsmngr/opsmngr.go
=> CLOUDP-68494: Add whitelist support to ops manager go client

opsmngr/global_api_key_whitelists.go, opsmngr/global_api_key_whitelists_test.go, opsmngr/opsmngr.go
=> CLOUDP-69664: [go-client] add global whitelist support

opsmngr/users.go
=> CLOUDP-70714: add mobile number to the User struct ops manager go client

opsmngr/opsmngr.go, opsmngr/projects.go, opsmngr/projects_test.go, opsmngr/teams.go, opsmngr/teams_test.go, opsmngr/users.go
=> CLOUDP-70780: Add support for teams in Ops Manager client

opsmngr/organizations.go, opsmngr/organizations_test.go
=> CLOUDP-70838: Update ListUsers to return a object instead of an array ops manager go client

.tool-versions, .travis.yml, README.md, go.mod
=> chore: update supported go versions

opsmngr/projects.go, opsmngr/projects_test.go
=> CLOUDP-70846: Add api call /groups/{PROJECT-ID}/teams to ops manager go client

opsmngr/maintenance.go
=> CLOUDP-72556: Update MaintenanceWindow to include omitempty in ops manager go client

go.mod, go.sum, opsmngr/opsmngr.go, opsmngr/performance_advisor.go, opsmngr/performance_advisor_test.go
=> CLOUDP-72804: Add Performance Advisor API call to opsmanger go client

opsmngr/agents.go, opsmngr/agents_test.go
Add the client for global agent versions
=> feat: add global software versions

opsmngr/opsmngr.go, opsmngr/version_manifest.go, opsmngr/version_manifest_test.go
=> CLOUDP-73628: Add Version manifest to the opsmanager go client

opsmngr/backup_configs.go, opsmngr/backup_configs_test.go, opsmngr/opsmngr.go
=> CLOUDP-73696: Implement backup configuration ops manager go client

opsmngr/version_manifest.go, opsmngr/version_manifest_test.go
=> CLOUDP-73982: Addressing PR comments in CLOUDP-73628

opsmngr/feature_control_policies.go, opsmngr/feature_control_policies_test.go, opsmngr/opsmngr.go
_Jira ticket:_ CLOUDP-75083
Endpoints: https://docs.opsmanager.mongodb.com/current/reference/api/feature-control-policies/
=> CLOUDP-75083: Implementing Feature Control Policies api for ops-manager go client

opsmngr/feature_control_policies.go, opsmngr/feature_control_policies_test.go, opsmngr/opsmngr.go
_Jira ticket:_ CLOUDP-75088
Fixes for issues that I found during the implementation of the featurePolicy command in mongocli
=> CLOUDP-75088: Removing -id from FeaturePolicy - ops manager go client

atmcfg/atmcfg.go, atmcfg/atmcfg_test.go
Add method to restart clusters
=> feat: allow to restart clusters

opsmngr/opsmngr.go
=> CLOUDP-80633: Update go.mongodb.org/atlas on ops manager go client

.github/workflows/pr.yml, .tool-versions, go.mod
=> build: add go1.16 support

README.md
=> docs: Update API docs link

.github/workflows/pr.yml, Makefile
=> lint: update GOLANGCI_VERSION to 1.37.0

atmcfg/atmcfg.go, atmcfg/atmcfg_test.go, atmcfg/fixtures.go
=> feat: add a method to reclaim free space on a cluster

README.md
Improve the code example in README by introducing the SetBaseURL and adding OpsManagerURL to ease the  beginners journey using this client.
- [] I have added tests that prove my fix is effective or that my feature works
=> Improve code example by adding OpsManagerURL for beginners

.github/CODEOWNERS, .github/dependabot.yml
=> task: add CODEOWNERS

.github/workflows/pr.yml, .golangci.yml, Makefile, atmcfg/atmcfg.go, atmcfg/atmcfg_test.go, atmcfg/fixtures.go, atmcfg/security.go, opsmngr/agents_api_keys.go, opsmngr/automation_config.go, opsmngr/automation_config_test.go, opsmngr/backup_agent_config.go, opsmngr/blockstore_config.go, opsmngr/logs.go, opsmngr/logs_test.go, opsmngr/opsmngr_test.go, opsmngr/server_usage.go, opsmngr/version_manifest.go, search/example_search_test.go, search/search_test.go
Update golangci and enable a new linter for json tags, this may be handy to prevent copy past errors, we had those before and it caught one on this PR
=> feat: update golangci and enable tagliatelle

.golangci.yml, atmcfg/atmcfg.go, opsmngr/automation_config.go, opsmngr/backup_configs.go, opsmngr/blockstore_config.go, opsmngr/daemon_config.go, opsmngr/feature_control_policies.go, opsmngr/file_system_store_config.go, opsmngr/oplog_store_config.go, opsmngr/opsmngr.go, opsmngr/project_job_config.go, opsmngr/s3_blockstore_config.go, opsmngr/server_usage.go, opsmngr/sync_store_config.go
Enable linting for docs on exported methods and fix the bad copy/paste on some of them
=> docs: enable exported lint and fix docs

go.mod, go.sum, opsmngr/opsmngr.go
_Jira ticket:_ 
- [] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added any necessary documentation (if appropriate)
- [] I have run `make fmt` and formatted my code
=> Upgrade Atlas go client

go.mod, opsmngr/accesslist_api_keys.go, opsmngr/accesslist_api_keys_test.go, opsmngr/alert_configurations.go, opsmngr/alert_configurations_test.go, opsmngr/alerts.go, opsmngr/alerts_test.go, opsmngr/continuous_restore_jobs.go, opsmngr/continuous_restore_jobs_test.go, opsmngr/continuous_snapshots.go, opsmngr/continuous_snapshots_test.go, opsmngr/events.go, opsmngr/events_test.go, opsmngr/global_api_keys.go, opsmngr/global_api_keys_test.go, opsmngr/opsmngr.go, opsmngr/organization_api_keys.go, opsmngr/organization_api_keys_test.go, opsmngr/organization_whitelist_api_keys.go, opsmngr/organization_whitelist_api_keys_test.go, opsmngr/project_api_keys.go, opsmngr/project_api_keys_test.go
=> CLOUDP-92301: Add the implementation of the services that were reused in the atlas go client [ops-manager go client]

opsmngr/alert_configurations.go, opsmngr/alert_configurations_test.go
=> Fixed path alertConfigs/matchers/fieldNames

go.mod, go.sum, opsmngr/organization_invitations.go, opsmngr/organization_invitations_test.go, opsmngr/organizations.go
Added Programmatic Invite Management for organization to the ops manager go client
_Jira ticket:_ CLOUDP-93383
=> CLOUDP-93383: Add Programmatic Invite Management for organization to the ops manager go client

go.mod, go.sum, opsmngr/project_invitations.go, opsmngr/project_invitations_test.go, opsmngr/projects.go
Added Programmatic Invite Management for projects to the opsmanager go client
_Jira ticket:_ CLOUDP-93384
=> CLOUDP-93384: Add Programmatic Invite Management for project to the opsmanager go client

opsmngr/organization_invitations.go, opsmngr/organization_invitations_test.go, opsmngr/organizations.go, opsmngr/project_invitations.go, opsmngr/project_invitations_test.go, opsmngr/projects.go
Bug: The Request Body Parameters `ID`, `OrgID`, `GroupID` must be blank when using `POST`, `PATCH` endpoints
=> Fixed Invite New User endpoints for organizations and projects

atmcfg/atmcfg.go, atmcfg/atmcfg_test.go
=> CLOUDP-94693:  Restart the entire cluster or a set of processes (ops manager go client)

opsmngr/automation_config.go
=> CLOUDP-96364: Added Horizons field to automation config

opsmngr/automation_config.go
=> feat: add DefaultRWConcern to automation config

.github/workflows/pr.yml, .golangci.yml, Makefile, opsmngr/deployments_hosts_test.go, opsmngr/diagnostics_test.go, opsmngr/global_alerts_test.go, opsmngr/global_api_key_whitelists_test.go, opsmngr/global_api_keys_test.go, opsmngr/opsmngr_test.go, opsmngr/project_api_keys_test.go, opsmngr/projects_test.go, opsmngr/teams_test.go, search/search_test.go
=> build (lint): update golangci-lint to 1.42.0

Makefile, atmcfg/atmcfg.go, atmcfg/atmcfg_test.go, atmcfg/fixtures.go, go.sum, opsmngr/automation_status.go, opsmngr/organization_invitations.go
Adds a new helper to check automation status
=> feat: add a helper to know automation reached goal state

opsmngr/version_manifest.go, opsmngr/version_manifest_test.go
Updating version manifest broken static path.
_Jira ticket:_  CLOUDP-98804
=> CLOUDP-98804: Fix update version manifest static path

opsmngr/automation_config.go
=> feat: add support for newAutoPwd

opsmngr/opsmngr.go
When we started with this client we didn't need all the methods, now that we do we can copy the atlas way of doing this to avoid the code duplication
=> task: small refactor for new request matching atlas

opsmngr/projects.go, opsmngr/projects_test.go
=> CLOUDP-108904: Add support for withDefaultAlertsSettings for creating a new project in the ops manager go client

opsmngr/agents.go, opsmngr/agents_test.go
Old bug we missed pagination here
=> feat: add pagination to agent listing

opsmngr/automation_config.go
Add  new `auditLogRotate` to the `processes` structure
_Jira ticket:_ CLOUDP-112076
=> CLOUDP-112076: Add new field to the process structure

.github/workflows/pr.yml, Makefile
Add go1.18 as a tested version
=> task: add go 1.18 to the test matrix

opsmngr/server_usage.go
=> CLOUDP-132496: MongoCLI server usage download results in only redacted version

opsmngr/organizations.go
Add support to filter projects by name making the API call compatible with the Atlas client
=> fix: add support to filter projects by name

.githooks/workflows/stale.yml, CONTRIBUTING.md
=> CLOUDP-79100: Autoclose stale issues and PRs

opsmngr/opsmngr.go
It allows us to easily mock http calls. 
Closes #166 
very small none break change
=> chore: replaced raw http client with interface

opsmngr/snapshot_schedule.go, opsmngr/snapshot_schedule_test.go
_Jira ticket:_  CLOUDP-162753
Allow zero(0) values for retention settings
=> CLOUDP-162753: [go] allow zero values for SnapshotSchedule

.github/workflows/pr.yml, .golangci.yml, Makefile
Update to lastest golang linter and update some rules
=> task: update linter and rules

opsmngr/automation_config_test.go
Add a test for the sharding section in the automation config
=> test: add deserialization test for sharding

opsmngr/automation_config.go
Adds some missing fields to log rotation struct
=> fix: add missing fields to automation config

opsmngr/accesslist_api_keys.go, opsmngr/continuous_restore_jobs.go, opsmngr/measurements.go, opsmngr/measurements_databases.go, opsmngr/measurements_disks.go, opsmngr/measurements_hosts.go, opsmngr/opsmngr.go, opsmngr/organization_api_keys.go
More alias to allow removing more references to the atlas SDK when ops manager only
=> feat: more alias to atlas types

opsmngr/opsmngr.go
Hopefully last round of alias needed on the CLI
=> task: missing alias

.github/CODEOWNERS
Removing APIx as codeowners of the client
=> task: transfer ownership

.github/dependabot.yml
Update the team assignment for dependabot
=> task: update dependabot team assigment

go.sum, opsmngr/automation_config.go
- Add `backupRestoreIsSuccessiveUpgrade` missing field to the `Process` struct
Jira ticket: [CLOUDP-283933](https://jira.mongodb.org/browse/CLOUDP-283933)
=> CLOUDP-283933: Add backupRestoreIsSuccessiveUpgrade field

.github/workflows/pr.yml, .golangci.yml, atmcfg/auth.go
We are upgrading the linter to 2.0.1, that requires upgrading the configs along with solving any linting issues resulted from this upgrade.
=> Upgrade linter and fix issues
