opsmngr/checkpoints.go
opsmngr/global_alerts.go
opsmngr/global_alerts_test.go
opsmngr/opsmngr.go

_Jira ticket:_ [CLOUDP-57847](https://jira.mongodb.org/browse/CLOUDP-57847)

CLOUDP-57847: Implement global alerts resource in ops manager client

---

atmcfg/randgen.go
atmcfg/randgen_test.go
opsmngr/deployments.go
opsmngr/diagnostics_test.go

I just spotted this, we don't block PRs if we fail on go master so that's probably why we did not know bit it looks like go1.15 may had broken the client

fix: go tip seems to be more careful with some castings

---

opsmngr/opsmngr.go
opsmngr/organizations.go
opsmngr/organizations_test.go
opsmngr/projects.go
opsmngr/projects_test.go
opsmngr/unauth_users.go
opsmngr/users.go
opsmngr/users_test.go

This adds methods for IAM users in OM
_Jira ticket:_ CLOUDP-70161
- [] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added any necessary documentation (if appropriate)
- [] I have run `make fmt` and formatted my code

CLOUDP-70161: add IAM users to client

---

opsmngr/maintenance.go
opsmngr/maintenance_test.go
opsmngr/opsmngr.go

CLOUDP-72553: add maintenance windows api to ops manager go client

---

opsmngr/file_system_store_config.go
opsmngr/file_system_store_config_test.go

CLOUDP-74339: Update FileSystemStoreConfiguration to include BackupStore in the ops manager go client

---

opsmngr/users.go

_Jira ticket:_ CLOUDP-74926
The Create user endpoint for CM requires the field Country https://docs.cloudmanager.mongodb.com/reference/api/user-create/. This field wasn’t included in the user struct because the same endpoint for OM doesn’t use this field. (https://docs.opsmanager.mongodb.com/current/reference/api/user-create/)

CLOUDP-74926: Add field country in User - ops manager go client

---

atmcfg/atmcfg.go
atmcfg/atmcfg_test.go

While testing the CLI for an advance remove command, https://github.com/mongodb/mongocli/pull/510, I realized we have a bug in shutdown for sharded clusters where mongos and config rs are left unmodified. 
Fixing this and adding tests to catch it also exposed the same bug for the remove method, so here we are fixing two bugs for one

fix: shutdown and remove for sharded clusters now works for config rs and mongos

---

opsmngr/opsmngr.go

_Jira ticket:_ CLOUDP-76488
This solve one of the network errors but broken pipe seems to still be a problem

CLOUDP-76488: [mongocli] patching the automation config can produce random network errors

---

atmcfg/atmcfg.go
atmcfg/atmcfg_test.go

_Jira ticket:_ CLOUDP-77074
I implemented this as a quick way to test the automation config endpoint via disabling/enabling monitoring

CLOUDP-77074: [go-client] allow to disable monitoring/backup

---

go.mod
go.sum
opsmngr/automation_config.go
opsmngr/automation_config_test.go
opsmngr/opsmngr.go
opsmngr/opsmngr_test.go

- add support to get raw automation config data (allow users to make config backup/compare changes in config)
- `.atlasProxies`/`.filebeat` to support cloud manager automation config
- `.mongosqlds`/`.onlineArchiveModules`/`.mongots` should not be tagged as `omitempty` to prevent unnecessary changes in automation config
- `.uiBaseUrl`/`.replicaSets.members.[].Tags`  should be tagged as `omitempty` to prevent unnecessary changes in automation config
- `.auth.usersDelete.customData`/`.auth.usersWanted.customData` to fully support ops manager automation config

Fix fields values. Add raw config getter

---

atmcfg/fixtures.go
opsmngr/automation_config.go
opsmngr/automation_config_test.go
search/example_search_test.go

Field `slaveDelay` is going to be replaced by `secondaryDelaySecs`. Let's support both of them
Doc changes: https://github.com/mongodb/docs/commit/bfcde5ee32c1857b744fcbc1693123220beaa06a
Related doc changes ticket: https://jira.mongodb.org/browse/DOCS-14169
_Jira ticket:_ 
https://jira.mongodb.org/browse/CLOUDP-89947

CLOUDP-89947: Add new memberConfig's secondaryDelaySecs field for FCV > 5

---

opsmngr/automation_config.go

This fixes the wrong type casting for the auth restrictions, is an object and not a string

fix: authenticationRestrictions typing

---

opsmngr/automation_config.go
opsmngr/automation_config_test.go

Add AutoPEMKeyFilePwd  to AutomationConfig.
_Jira ticket:_  https://jira.mongodb.org/browse/CLOUDP-92485
AutoPEMKeyFilePwd is not being pared by GET calls from Ops Manager. As a result, subsequent PUT requests will clear the existing config value and remove the password setting.
- [] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [] I have added any necessary documentation (if appropriate)
- x] I have run `make fmt` and formatted my code

CLOUDP-92485: Add AutoPEMKeyFilePwd to automation config

---

opsmngr/project_invitations.go

Bug: we were setting the wrong `invitationID`

Fixed the endpoint that allows to update an invitation

---

opsmngr/organization_invitations.go
opsmngr/project_invitations.go

Bug: we were setting the wrong `invitationID`
_Jira ticket:_

Fixed the endpoint that allows to update an invitation for organisation

---

atmcfg/atmcfg.go
atmcfg/atmcfg_test.go

CLOUDP-94859: allow to reclaim free space for processes [ops manager go client]

---

.github/workflows/pr.yml
Makefile

Github recomments to just use the major, I think this got bumped as par of dependabot let's see if dependabot stops trying to add minor versions here

test: test actions with only major version

---

go.mod
go.sum
opsmngr/projects.go
opsmngr/projects_test.go

Description:
Added query param [projectOwnerId](https://docs.atlas.mongodb.com/reference/api/project-create-one/#request-query-parameters) to `Projects.Create`
_Jira ticket:_ 
- [] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added any necessary documentation (if appropriate)
- [] I have run `make fmt` and formatted my code

[Mongocli - Cloud manager] Add support for projectOwnerId with project creation/modification

---

.github/workflows/pr.yml
Makefile
opsmngr/accesslist_api_keys.go
opsmngr/accesslist_api_keys_test.go
opsmngr/agents_api_keys.go
opsmngr/global_api_key_whitelists.go
opsmngr/global_api_keys.go
opsmngr/global_api_keys_test.go
opsmngr/opsmngr.go
opsmngr/opsmngr_test.go
opsmngr/organization_api_keys.go
opsmngr/organization_api_keys_test.go
opsmngr/organization_whitelist_api_keys.go
opsmngr/organization_whitelist_api_keys_test.go
opsmngr/project_api_keys.go

_Jira ticket:_ CLOUDP-105826
Linting now flags `ioutil` as deprecated, which it is and gosec is a bit more aggressive and picking up some false positives

CLOUDP-105826: Update golangci-lint to 1.43

---

opsmngr/automation_config.go
opsmngr/automation_config_test.go

Adds Force property to `opsmngr.AutomationConfig.ReplicaSets`
Closes #130 
Simple change to add a parameter to existing structures used for API calls.

fix: add force object to automation config replicaset object

---

opsmngr/automation_config.go
opsmngr/opsmngr.go

This properties are not string and failing to be deserialized, moving to interface for now

fix: Change backup options to interfaces

---

opsmngr/opsmngr.go

This workaround was a fix around older versions of go which is no longer needed

fix: clean up close body workaround

---

opsmngr/opsmngr.go
opsmngr/opsmngr_test.go

_Jira ticket:_ CLOUDP-114669
Original PR: https://github.com/mongodb/go-client-mongodb-atlas/pull/281

CLOUDP-114669: Automatically add trailing slash to the URL

---

opsmngr/feature_control_policies.go

To disable feature controls you need to pass an empty list, since we had ignore empty this were not being serialized and some versions of ops managers will error with 500 when null

fix: allow empty policies for feature controls

---

atmcfg/atmcfg.go
atmcfg/atmcfg_test.go
atmcfg/fixtures.go
atmcfg/remove.go
atmcfg/remove_test.go
atmcfg/suspend.go
atmcfg/suspend_test.go

Add a method to suspend automation for a cluster, or processes of a cluster 
Follows the same patters we have used for actions like restart, compact space or similar

feat: add suspend automation method

---

go.mod
go.sum

Manual updated to latest stable since pseudo versions are not picked up by dependabot

task: update go.mongodb.org/atlas to v0.17.0

---

.github/workflows/pr.yml

Drop support for 1.17 which is in line with our support policy of two latets major releases to unblock pointy lib upgrade

task: drop go 1.17 support

---

.github/workflows/pr.yml
.golangci.yml
Makefile
opsmngr/agents_api_keys_test.go
opsmngr/alert_configurations_test.go
opsmngr/alerts_test.go
opsmngr/checkpoints_test.go
opsmngr/clusters_test.go
opsmngr/continuous_restore_jobs_test.go
opsmngr/continuous_snapshots_test.go
opsmngr/deployments_hosts_test.go
opsmngr/diagnostics_test.go
opsmngr/events_test.go
opsmngr/feature_control_policies_test.go
opsmngr/global_api_key_whitelists_test.go
opsmngr/logs_test.go
opsmngr/maintenance_test.go
opsmngr/measurements_hosts_test.go
opsmngr/organizations_test.go
opsmngr/project_api_keys_test.go
opsmngr/project_invitations_test.go
opsmngr/projects_test.go
opsmngr/server_usage_test.go
opsmngr/snapshot_schedule_test.go
opsmngr/teams_test.go
opsmngr/users_test.go

Update golangci linter and do some clean up

task: update golangci lint

---

opsmngr/alert_configurations.go
opsmngr/opsmngr.go

Add a couple of alias that the CLI still references via atlas client when the commands are ops manager only now and thus allowing the removal of the old client

feat: add alias to Atlas structs to simplify migration from atlas client

---

opsmngr/live_data_migration.go
opsmngr/measurements.go
opsmngr/opsmngr.go

Another pass on alias needed to remove references to the legacy SDK

feat: some more alias to atlas client types

---

opsmngr/opsmngr.go

Reduce direct dependencies on atlas go client by providing alias

task: missing alias to remove direct dependencies on atlas

---

opsmngr/checkpoints.go
opsmngr/checkpoints_test.go
opsmngr/continuous_restore_jobs.go
opsmngr/continuous_snapshots.go
opsmngr/continuous_snapshots_test.go
opsmngr/diagnostics.go
opsmngr/logs.go
opsmngr/opsmngr.go
opsmngr/performance_advisor.go
opsmngr/performance_advisor_test.go
opsmngr/snapshot_schedule.go

Phase 2 of: https://github.com/mongodb/go-client-mongodb-ops-manager/pull/231

 CLOUDP-252326: Remove Atlas Dependency Phase 2

---

auth/device_flow.go
auth/device_flow_test.go
auth/oauth.go
auth/oauth_test.go
auth/token.go
opsmngr/opsmngr.go
opsmngr/opsmngr_test.go

Related to: https://github.com/mongodb/go-client-mongodb-ops-manager/pull/231
Adding Auth dependencies required by Mongodb-CLI

CLOUDP-252326 add missing auth dependencies

---

.github/workflows/pr.yml
atmcfg/auth.go
atmcfg/security.go
atmcfg/security_test.go
auth/device_flow_test.go
opsmngr/accesslist_api_keys.go
opsmngr/accesslist_api_keys_test.go
opsmngr/agents_api_keys.go
opsmngr/agents_api_keys_test.go
opsmngr/alert_configurations_test.go
opsmngr/alerts_test.go
opsmngr/automation_config.go
opsmngr/checkpoints_test.go
opsmngr/continuous_snapshots_test.go
opsmngr/events_test.go
opsmngr/global_api_key_whitelists.go
opsmngr/global_api_key_whitelists_test.go
opsmngr/global_api_keys.go
opsmngr/global_api_keys_test.go
opsmngr/maintenance_test.go
opsmngr/organization_api_keys.go
opsmngr/organizations_test.go
opsmngr/project_api_keys.go
opsmngr/teams_test.go
opsmngr/users.go
opsmngr/users_test.go

_Jira ticket:_  CLOUDP-271909
Closes #239

CLOUDP-271909: fix deleted user struct

---

opsmngr/automation_config.go
opsmngr/automation_config_test.go

**Current behaviour:**
Prometheus configuration is missing from the AutomationConfig when we get it via the opsmngr [GetConfig](https://github.com/mongodb/go-client-mongodb-ops-manager/blob/c93a707acdb1090bdd51c05f5a5a9ba69ec6a4dc/opsmngr/automation_config.go#L24) call. We can see it is missing from [the AutomationConfig struct](https://github.com/mongodb/go-client-mongodb-ops-manager/blob/c93a707acdb1090bdd51c05f5a5a9ba69ec6a4dc/opsmngr/automation_config.go#L68). However, [prometheus configuration is present when we get it directly from the opsmanager API](https://www.mongodb.com/docs/ops-manager/current/reference/api/automation-config/get-automation-config/).
**Proposed behaviour:**
Prometheus configuration will be properly handled and returned in opsmngr GetConfig and UpdateConfig …

fix: add missing prometheus config to AutomationConfig

---

opsmngr/automation_config.go

- Make `backupRestoreIsSuccessiveUpgrade` field a pointer so that `omitempty` doesn't remove it from the payload when the value is `false`
- *Note*: This is a _breaking_ change, but nobody should be using the field, as it's for internal use.
_Jira ticket:_ [CLOUDP-295783](https://jira.mongodb.org/browse/CLOUDP-295783)

CLOUDP-295783: Make backupRestoreIsSuccessiveUpgrade a pointer
